### ISSUE TITLE
Training the model requires how much VRAM?

### ISSUE THREAD

**Issue by pi1412** [WeihaoTan/TWOSOME#1]
Even with A100-80G, in order to successfully run tomato_salad_ppo_llm.sh, parameters can only be set to:

python twosome/overcooked/ppo_llm_pomdp.py \
  --exp-name "tomato_salad_llm"\
  --policy-learning-rate 5e-7 \
  --value-learning-rate 1e-5 \
  --num-envs 1 \
  --num-steps 28 \
  --policy-num-minibatches 1 \
  --value-num-minibatches 1 \
  --update-epochs 1 \
  --total-timesteps 500000 \
  --critic-warm-up-steps 0 \
  --env-reward 0.2 1 0.1 0.001 \
  --target-kl 0.02 \
  --gradient-checkpointing-steps 8 \
  --task 0 \
  --env-id "Overcooked-LLMA-v4" \
  --record-path "workdir" \
  --normalization-mode "word" \

**Comment by WeihaoTan** [comment]
Hi, all our experiments can be run within A100 40G. policy-num-minibatches and value-num-minibatches should not be set to 1. They actually mean how many minibatches a batch has. 1 means that you are using the whole batch to train, which will need large VRAM to run.
