### ISSUE TITLE
Questions on overcooked environment

### ISSUE THREAD

**Issue by yanxue7** [WeihaoTan/TWOSOME#10]
Dear authors,

I really appreciate your work, especially on Overcooked, which is a commonly used environment in the RL domain.

I attempted to test the LLM Tomato-Salad Overcooked environment:

I created an environment as follows:

```
env_params = {'grid_dim': args.grid_dim,
                  'task': TASKLIST[args.task],
                  'rewardList': rewardList,
                  'map_type': args.map_type,
                  'n_agent': args.n_agent,
                  'obs_radius': args.obs_radius,
                  'mode': args.mode,
                  'debug': args.debug
                  }
env_id=Overcooked-LLMA-v4
    env = gym.make(env_id, **env_params)

``` 

I noticed that for the first step observation, it’s an integer vector. However, when I take action 0 (pick up the tomato), the next step observation becomes a float vector, and the prompt shows, "There is a fixed cutting board in the room. Currently, you don't have anything in hand." It seems that no tomato is held in hand. In most previous implementations of Overcooked, the observations are usually integers.

So, I’m wondering if the float observation vector is normal in your implementation. If not, are there any mistakes in my implementation for creating the environment?

```
Overcooked-LLMA-v4__overcooked__1

[0 5 0 6 5 1 0 3 0 1 4 1 0 0 0 0 0 0]

{'prompt': "There is a fixed cutting board in the room. You notice a tomato and a bowl on the different tables. Currently you don't have anything in hand. To serve the dish of a bowl only containing chopped tomato, you should first", 'action': ['pick up the tomato', 'take the bowl', 'walk to the cutting board', 'serve nothing', 'chop nothing']}

Action:0

[array([0.    , 0.71428571, 0.    , 0.85714286, 0.71428571,

​    0.14285714, 0.    , 0.42857143, 0.    , 0.14285714,

​    0.71428571, 1.    , 0.    , 0.    , 0.    ,

​    \0.    , 0.    , 0.    ])]

{'prompt': "There is a fixed cutting board in the room. Currently you don't have anything in hand. To serve the dish of a bowl only containing chopped tomato, you should first", 'action': ['pick up the tomato', 'take the bowl', 'walk to the cutting board', 'serve nothing', 'chop nothing']}

-0.001

Action:
```

**Comment by WeihaoTan** [comment]
Thanks for reaching out. I am not sure why this happens. The output should be integer. Did you wrap the env with 
env = MacEnvWrapper(env)?

**Comment by yanxue7** [comment]
Thanks for your help! I solved this problem using the wrapper env = MacEnvWrapper(env).
