### ISSUE TITLE
Bug when do not set CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by Felixvillas** [WeihaoTan/TWOSOME#5]
Hi~ 
I found that when I do not set `CUDA_VISIBLE_DEVICES=0`, the code using multiple GPU by default, and there is a bug:
```bash
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```
when `outputs = self.actor(input_ids, attention_mask=attention_mask)`.
I'm not sure if this is a bug. If so, could you please fix it?

**Comment by WeihaoTan** [comment]
It is not a bug. Please set CUDA_VISIBLE_DEVICES before you run, just like what we showed in the scripts, which makes it easier for us to run multiple experiments on a machine or cluster with several GPUs. Feel free to change the code as long as it is more convenient for you.
