### ISSUE TITLE
I have a question about how macro actions work.

### ISSUE THREAD

**Issue by TuZzzz1** [WeihaoTan/TWOSOME#7]
Really appreciate your work, but I have got one problem I can't really understand from the code.
So there is a process where you transfer macro actions like 'Go Cutting-board 1' into a sequence of micro actions like 'right' 'down' 'stay'. And you highlight that it is a partial ovservation which means that the agent is only given a 5*5 observation. In that case , for example, if the cutting-board is not observed by the agent ,and the agent takes 'Go Cutting-board 1' as its action, how will it work? This is the case in appendix figure c.What will agent do to get to the destination.
 Do you suppose that it doesn't matter if the agent can observe the cutting-board? As long as the agent take the 'go someplace' action, it will go to the destination?
I am really confuse. I will be grateful if you guys can kindly answer my question.
Actually , I can't quite understand def _computeLowLevelActions(self, macro_actions) and def _navigate(self, agent, target_x, target_y): in TWOSOME/gym-macro-overcooked/gym_macro_overcooked/overcooked_LLMA_V1.py.

**Comment by TuZzzz1** [comment]
![image](https://github.com/user-attachments/assets/5cf9d433-8bb7-4214-92c2-7e481987decf)
I mean this case, from b to c, the cutting board is not observable by the agent in figure b.So how can it get the cutting board in figure c?

**Comment by WeihaoTan** [comment]
Thanks for reaching out. In this env, each macro action is initialized with the initial position of each item. So for the fixed object, like a cutting board, even if it is not observed, the macro action can still guide the agent to the place. For the movable objects, the macro action will navigate the agent to the place where the item was observed last time under partial observability.

**Comment by TuZzzz1** [comment]
Thanks for your replies. Do you think it is a bit paradoxical that while it is a partial obsevable environment but the agent still can reach out the items out of its observation without any exploration? By the way, is the actions space of PPO and TWOSOME totally same? Because I think macro actions may contain too much priori human-made information, so it may be a bit unfair for PPO?
Anyway ,it's a great work and enlightens me a lot. I am just a bit confused and will be grateful if you can answer my question.

**Comment by WeihaoTan** [comment]
From my understanding, even provided with a map, the partial observable env is still challenging, which is actually a common setting in Robotics. As for the action space, they are exactly the same for PPO and TWOSOME but TWOSOME can leverage the semantics and PPO can only use the index. And I do not think it is unfair for PPO. The fact is that for any environment, each action has already had its own semantics when designing the action space. But traditional RL algorithms have been failing to leverage it.

**Comment by TuZzzz1** [comment]
> From my understanding, even provided with a map, the partial observable env is still challenging, which is actually a common setting in Robotics. As for the action space, they are exactly the same for PPO and TWOSOME but TWOSOME can leverage the semantics and PPO can only use the index. And I do not think it is unfair for PPO. The fact is that for any environment, each action has already had its own semantics when designing the action space. But traditional RL algorithms have been failing to leverage it.

thanks for your replies, that help me a lot. I will close this issue as completed.
