### ISSUE TITLE
Issue about environment visualization in Virtualhome

### ISSUE THREAD

**Issue by Tomshine123** [WeihaoTan/TWOSOME#8]
Thanks for your great work, by the clear instructions I have successfully run the demo of training. But as I run the scripts of Virtualhome tasks there is no environment visualized besides the text information, is this a bug or any settings need to be changed to render it?

**Comment by WeihaoTan** [comment]
Thanks for reaching out. VirtualHome provides two envs, python version (the version we use in the code) and Unity3D version(exec). Python version directly works on the node file without rendering the env, which is more efficient for training. Unity 3D version renders the env with the node file so you can get images and video from the env but with a much slower speed. You need to follow the VirtualHome docs to install and deploy your agent to the unity3D version to visualize it.

**Comment by Tomshine123** [comment]
I tried with tutorials of VirtualHome and successfully rendered the scene with scripts converted from evolving graph environment. Thanks for your response with great help!
