### ISSUE TITLE
An error occurred when normalization was set to sum.

### ISSUE THREAD

**Issue by dingbiao12** [WeihaoTan/TWOSOME#9]
When I set the normalization mode in the script file to sum, the return in the training process is basically 0. May I ask what is going on？Thanks

**Comment by WeihaoTan** [comment]
Thanks for reaching out. Could you provide more details? Like which envs and scripts you used. Did you modify any parameters? 
Does the return have been 0 during the whole training process or it use to be a number and then drop to 0? And did you try to run word normalization and check whether the return is 0, either?

**Comment by dingbiao12** [comment]
The environment I ran was Virtualhome-v1, the script I ran was food_preparation_ppo_llm.sh, I set the nomorlization mode to sum, and did not modify any other parameters. The return value is normal when running word normalization and token normalization, but the return value is basically 0 when the parameter is set to sum

**Comment by WeihaoTan** [comment]
Sum means TWOSOME without normalization, which is not an ideal method and does not guarantee to have good performance. If you really want to explore its performance, you can run multiple times with different seeds.
